update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "Steamo.xcodeproj"
    )

    build_app(export_xcargs: "-allowProvisioningUpdates", workspace: "Steamo.xcworkspace", scheme: "Steamo")
    upload_to_testflight

    commit_version_bump(xcodeproj: "Steamo.xcodeproj")
    push_to_git_remote
  end
end
